name: Send email reminder test

on:
  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Install msmtp
        run: |
          sudo apt-get update
          sudo apt-get install msmtp

      - name: Send email reminder
        env:
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
        run: |
          echo "Тестирование отправки email..."
          
          # Настроим msmtp для использования с SMTP сервером
          echo "
          account default
          host $SMTP_SERVER
          port $SMTP_PORT
          auth on
          user $EMAIL_USER
          password $EMAIL_PASSWORD
          from $EMAIL_USER
          tls on
          " > ~/.msmtprc

          # Отправим email
          echo -e "Subject: Проверка уведомлений\n\nЭто тестовое напоминание." | msmtp $TO_EMAIL
