name: Send Email Notification

on:
  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Send email notification
        env:
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
        run: |
          echo "Отправка тестового уведомления по email..."
          python - <<'EOF'
import smtplib
from email.mime.text import MIMEText

msg = MIMEText('Это тестовое уведомление для проверки работы email.')
msg['Subject'] = 'Проверка уведомлений'
msg['From'] = '${{ secrets.EMAIL_USER }}'
msg['To'] = '${{ secrets.TO_EMAIL }}'

try:
    with smtplib.SMTP('${{ secrets.SMTP_SERVER }}', int('${{ secrets.SMTP_PORT }}')) as server:
        server.starttls()
        server.login('${{ secrets.EMAIL_USER }}', '${{ secrets.EMAIL_PASSWORD }}')
        server.sendmail('${{ secrets.EMAIL_USER }}', '${{ secrets.TO_EMAIL }}', msg.as_string())
    print("Уведомление отправлено успешно")
except Exception as e:
    print(f"Ошибка при отправке уведомления: {e}")
EOF


